"use client";

import { useState } from "react";

interface ReachOutHelperProps {
  summary: string;
  talkingPoints?: string[];
  professorName: string;
}

export default function ReachOutHelper({
  summary,
  talkingPoints,
  professorName,
}: ReachOutHelperProps) {
  const [isExpanded, setIsExpanded] = useState(false);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  const handleCopy = async (text: string, index: number) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedIndex(index);
      setTimeout(() => setCopiedIndex(null), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopiedIndex(index);
      setTimeout(() => setCopiedIndex(null), 2000);
    }
  };

  return (
    <div className="neu-card p-3 mb-4">
      <button
        onClick={() => setIsExpanded(!isExpanded)}
        className="w-full flex items-center justify-between text-left"
      >
        <div className="flex items-center gap-3">
          <div
            className="w-8 h-8 border-2 border-[#1a1a1a] flex items-center justify-center shrink-0"
            style={{ backgroundColor: "#6bcb77" }}
          >
            <span className="text-[#1a1a1a] font-bold text-sm">?</span>
          </div>
          <div>
            <h2 className="text-sm font-bold text-[#1a1a1a]">
              Help Me Reach Out
            </h2>
            <p className="text-xs text-[#666]">
              Tips for connecting with {professorName.split(" ")[0]}
            </p>
          </div>
        </div>
        <span className="text-[#1a1a1a] font-bold text-lg">{isExpanded ? "−" : "+"}</span>
      </button>

      {isExpanded && (
        <div className="mt-4 space-y-3 border-t-2 border-[#1a1a1a] pt-4">
          {/* Research Summary */}
          <div>
            <h3 className="text-xs font-bold text-[#1a1a1a] mb-2 uppercase tracking-wider">Research Focus</h3>
            <p className="text-xs text-[#666] bg-[#fffef5] border-2 border-[#1a1a1a] p-3">
              {summary}
            </p>
          </div>

          {/* Talking Points */}
          {talkingPoints && talkingPoints.length > 0 && (
            <div>
              <h3 className="text-xs font-bold text-[#1a1a1a] mb-2 uppercase tracking-wider">Suggested Talking Points</h3>
              <ul className="space-y-2">
                {talkingPoints.map((point, index) => (
                  <li
                    key={index}
                    className="flex items-start gap-2 text-xs text-[#1a1a1a] bg-[#fffef5] border-2 border-[#1a1a1a] p-3 group"
                  >
                    <span className="w-5 h-5 bg-[#ffd93d] border border-[#1a1a1a] flex items-center justify-center shrink-0 text-xs font-bold mt-0">
                      {index + 1}
                    </span>
                    <span className="flex-1">{point}</span>
                    <button
                      onClick={() => handleCopy(point, index)}
                      className="opacity-0 group-hover:opacity-100 transition-opacity p-1 text-[#1a1a1a] font-bold"
                      title="Copy to clipboard"
                    >
                      {copiedIndex === index ? "✓" : "✂"}
                    </button>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Disclaimer */}
          <p className="text-xs text-[#666] italic border-t-2 border-[#1a1a1a] pt-3">
            Generated by AI. Always personalize your outreach.
          </p>
        </div>
      )}
    </div>
  );
}
